# /etc/rsyslog.conf
# Custom configuration for Enterprise SIEM Lab

# -------------------------------------------------------
# MODULES
# -------------------------------------------------------
# Provide UDP syslog reception
module(load="imudp")
input(type="imudp" port="514")

# -------------------------------------------------------
# CUSTOM ROUTING RULES
# -------------------------------------------------------
# Catch all Cisco IOS logs coming from the lab subnets
# Route them to a dedicated file and stop processing to keep syslog clean

:fromhost-ip, startswith, "192.168." /var/log/cisco-network.log
& stop